version: '2'
services:
    proxy_server-mongodb:
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/proxy_server/mongodb/:/data/db/
